<a href="https://colab.research.google.com/github/AchmadAinunNaim/Machlearning_Semester5-/blob/main/Minggu9/Praktikum04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Pra Pengolahan Data**

# Langkah 1 - import Library

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

# langkah 2 - Load Data

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Machlearning/Pertemuan 09/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values


cek data

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


# Langkah 3 - Encoding Kategorikal

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


# Langkah 4 - Encoding Kolom " Geography "dengan One Hot Encoder

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Langkah 5 - split Data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Langkah 6 - Scaling Fitur

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Membuat Model ANN

# langkah 1 - Inisiasi  Model ANN

In [ ]:
ann = tf.keras.models.Sequential()

# Langkah 2 - membuat input Layer dan Hilden Layer Pertama

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Langkah 3- Membuat Hideen Layar Kedua

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Langkah 4 - Membuat OutLayer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## **Training Model**

# Langkah 1 - Compile Model ( menyatukan Arsitektur ) ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Langkah 2 - Fitting Model

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5646 - accuracy: 0.7246
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4650 - accuracy: 0.7950
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4378 - accuracy: 0.8006
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4191 - accuracy: 0.8130
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4089 - accuracy: 0.8185
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4021 - accuracy: 0.8194
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3954 - accuracy: 0.8239
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3877 - accuracy: 0.8325
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3807 - accuracy: 0.8375
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3743 - accura

Diberikan informasi sebagai berikut,

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000    

# Modelkan Data Baru dan Buat Prediksi

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 328ms/step
[[False]]


# Prediksi Dengan Data Testing

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Cek Akurasi Dan Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1511   84]
 [ 200  205]]


0.858